package all

// Code generated by cmd/gen DO NOT EDIT.

import "fmt"

func AddFloat32(a, b, c []float32) {
	if len(a) != len(b) || len(a) != len(c) {
		panic(fmt.Errorf("incompatible lengths: %d, %d, %d", len(a), len(b), len(c)))
	}
	for len(a) >= 16 {
		c[0] = a[0] + b[0]
		c[1] = a[1] + b[1]
		c[2] = a[2] + b[2]
		c[3] = a[3] + b[3]
		c[4] = a[4] + b[4]
		c[5] = a[5] + b[5]
		c[6] = a[6] + b[6]
		c[7] = a[7] + b[7]
		c[8] = a[8] + b[8]
		c[9] = a[9] + b[9]
		c[10] = a[10] + b[10]
		c[11] = a[11] + b[11]
		c[12] = a[12] + b[12]
		c[13] = a[13] + b[13]
		c[14] = a[14] + b[14]
		c[15] = a[15] + b[15]

		a = a[16:]
		b = b[16:]
		c = c[16:]
	}
	for i := range c {
		c[i] = a[i] + b[i]
	}
}

func DivFloat32(a, b, c []float32) {
	if len(a) != len(b) || len(a) != len(c) {
		panic(fmt.Errorf("incompatible lengths: %d, %d, %d", len(a), len(b), len(c)))
	}
	for len(a) >= 16 {
		c[0] = a[0] / b[0]
		c[1] = a[1] / b[1]
		c[2] = a[2] / b[2]
		c[3] = a[3] / b[3]
		c[4] = a[4] / b[4]
		c[5] = a[5] / b[5]
		c[6] = a[6] / b[6]
		c[7] = a[7] / b[7]
		c[8] = a[8] / b[8]
		c[9] = a[9] / b[9]
		c[10] = a[10] / b[10]
		c[11] = a[11] / b[11]
		c[12] = a[12] / b[12]
		c[13] = a[13] / b[13]
		c[14] = a[14] / b[14]
		c[15] = a[15] / b[15]

		a = a[16:]
		b = b[16:]
		c = c[16:]
	}
	for i := range c {
		c[i] = a[i] / b[i]
	}
}

func MaxFloat32(a, b, c []float32) {
	if len(a) != len(b) || len(a) != len(c) {
		panic(fmt.Errorf("incompatible lengths: %d, %d, %d", len(a), len(b), len(c)))
	}
	for len(a) >= 16 {
		c[0] = max(a[0], b[0])
		c[1] = max(a[1], b[1])
		c[2] = max(a[2], b[2])
		c[3] = max(a[3], b[3])
		c[4] = max(a[4], b[4])
		c[5] = max(a[5], b[5])
		c[6] = max(a[6], b[6])
		c[7] = max(a[7], b[7])
		c[8] = max(a[8], b[8])
		c[9] = max(a[9], b[9])
		c[10] = max(a[10], b[10])
		c[11] = max(a[11], b[11])
		c[12] = max(a[12], b[12])
		c[13] = max(a[13], b[13])
		c[14] = max(a[14], b[14])
		c[15] = max(a[15], b[15])

		a = a[16:]
		b = b[16:]
		c = c[16:]
	}
	for i := range c {
		c[i] = max(a[i], b[i])
	}
}

func MinFloat32(a, b, c []float32) {
	if len(a) != len(b) || len(a) != len(c) {
		panic(fmt.Errorf("incompatible lengths: %d, %d, %d", len(a), len(b), len(c)))
	}
	for len(a) >= 16 {
		c[0] = min(a[0], b[0])
		c[1] = min(a[1], b[1])
		c[2] = min(a[2], b[2])
		c[3] = min(a[3], b[3])
		c[4] = min(a[4], b[4])
		c[5] = min(a[5], b[5])
		c[6] = min(a[6], b[6])
		c[7] = min(a[7], b[7])
		c[8] = min(a[8], b[8])
		c[9] = min(a[9], b[9])
		c[10] = min(a[10], b[10])
		c[11] = min(a[11], b[11])
		c[12] = min(a[12], b[12])
		c[13] = min(a[13], b[13])
		c[14] = min(a[14], b[14])
		c[15] = min(a[15], b[15])

		a = a[16:]
		b = b[16:]
		c = c[16:]
	}
	for i := range c {
		c[i] = min(a[i], b[i])
	}
}

func MulFloat32(a, b, c []float32) {
	if len(a) != len(b) || len(a) != len(c) {
		panic(fmt.Errorf("incompatible lengths: %d, %d, %d", len(a), len(b), len(c)))
	}
	for len(a) >= 16 {
		c[0] = a[0] * b[0]
		c[1] = a[1] * b[1]
		c[2] = a[2] * b[2]
		c[3] = a[3] * b[3]
		c[4] = a[4] * b[4]
		c[5] = a[5] * b[5]
		c[6] = a[6] * b[6]
		c[7] = a[7] * b[7]
		c[8] = a[8] * b[8]
		c[9] = a[9] * b[9]
		c[10] = a[10] * b[10]
		c[11] = a[11] * b[11]
		c[12] = a[12] * b[12]
		c[13] = a[13] * b[13]
		c[14] = a[14] * b[14]
		c[15] = a[15] * b[15]

		a = a[16:]
		b = b[16:]
		c = c[16:]
	}
	for i := range c {
		c[i] = a[i] * b[i]
	}
}

func SubFloat32(a, b, c []float32) {
	if len(a) != len(b) || len(a) != len(c) {
		panic(fmt.Errorf("incompatible lengths: %d, %d, %d", len(a), len(b), len(c)))
	}
	for len(a) >= 16 {
		c[0] = a[0] - b[0]
		c[1] = a[1] - b[1]
		c[2] = a[2] - b[2]
		c[3] = a[3] - b[3]
		c[4] = a[4] - b[4]
		c[5] = a[5] - b[5]
		c[6] = a[6] - b[6]
		c[7] = a[7] - b[7]
		c[8] = a[8] - b[8]
		c[9] = a[9] - b[9]
		c[10] = a[10] - b[10]
		c[11] = a[11] - b[11]
		c[12] = a[12] - b[12]
		c[13] = a[13] - b[13]
		c[14] = a[14] - b[14]
		c[15] = a[15] - b[15]

		a = a[16:]
		b = b[16:]
		c = c[16:]
	}
	for i := range c {
		c[i] = a[i] - b[i]
	}
}
